_wandb:
    value:
        cli_version: 0.22.2
        e:
            51v0dz8l4a890wws1709hii3knj4ovui:
                args:
                    - verify
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "59939684352"
                        used: "12000542720"
                email: karankaushik715@gmail.com
                executable: /root/wandb-take-home/bin/python3
                host: raspberrypi
                memory:
                    total: "3980316672"
                os: Linux-6.12.34+rpt-rpi-v8-aarch64-with-glibc2.36
                program: /root/wandb-take-home/bin/wandb
                python: CPython 3.11.2
                root: /home/karan/Desktop/wandb-take-home-assignment/wandb-take-home/runs
                startedAt: "2025-10-23T12:58:31.394477Z"
                writerId: 51v0dz8l4a890wws1709hii3knj4ovui
        m: []
        python_version: 3.11.2
        t:
            "3":
                - 2
                - 14
                - 16
            "4": 3.11.2
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": linux-aarch64
test:
    value: artifact log
