_wandb:
    value:
        cli_version: 0.22.2
        e:
            msope80mfdx3ozhfbqs8fkyai4v9f2uc:
                args:
                    - verify
                email: karankaushik715@gmail.com
                executable: /root/wandb-take-home/bin/python3
                host: raspberrypi
                os: Linux-6.12.34+rpt-rpi-v8-aarch64-with-glibc2.36
                program: /root/wandb-take-home/bin/wandb
                python: CPython 3.11.2
                root: /home/karan/Desktop/wandb-take-home-assignment/wandb-take-home/runs
                startedAt: "2025-10-23T12:57:58.995866Z"
                writerId: msope80mfdx3ozhfbqs8fkyai4v9f2uc
        m: []
        python_version: 3.11.2
        t:
            "3":
                - 2
                - 3
                - 14
                - 16
            "4": 3.11.2
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": linux-aarch64
test:
    value: put to graphql
